### PR TITLE
method 4 multiplication of all elements in the array

### PR DESCRIPTION
**Pull request by tatiana-tr**

### CODE REVIEW

**Review by arturchesnokov — APPROVED** [review]
getMultiplicationValues  - > getMultiplicationOfValues ??

**Review by YelyzavetaBerezhna — CHANGES_REQUESTED** [review]
please add a documentation comment before your method

**Comment by tatiana-tr** [comment]
method already has documentation "Returns the multiplication of all elements in the array."

**Comment by YelyzavetaBerezhna** [comment]
Please pay attention on the format of comment before 5th method

`/**`
`     * Method #5.`
`     * Returns the maximum element of the array.`
`     *`
`     * @author Girenko A.`
`     */`

**Review by nick8704 — APPROVED** [review]

**Review by alenagir — APPROVED** [review]

**Pull request closed without merging**
